# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Prep
        run: |
          python -V  
          pip install --upgrade bumpversion
          # Set git config
          git config --global user.email $GIT_USER_EMAIL
          git config --global user.name $GITHUB_ACTOR
          git config --global push.default simple
          # Install bumpversion
          pip install --upgrade bumpversion
          PATH="$PATH:$HOME/.local/bin"
          # Merge to main
          git checkout integration
          git checkout main
          git merge integration --no-edit
          # Bump Integration!
          git checkout integration
          bumpversion $BUMPVERSION_TYPE --list --verbose
          # Push Both Commits and Tags
          git push --all 
          git push --tags 
        env: 
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          BUMPVERSION_TYPE: patch


